[tool.poetry]
name = "pythonproject10"
version = "0.1.0"
description = ""
authors = ["Katrin <Carpe_diemsk@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
